// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnVlIbneXosHAkUYSVFFDuvgadnQeOCm4',
    appId: '1:100273539833:web:84dc58a3a9b0c012c93028',
    messagingSenderId: '100273539833',
    projectId: 'sikode-app',
    authDomain: 'sikode-app.firebaseapp.com',
    storageBucket: 'sikode-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZUfcjFgy4ZkhXFNkznOIGApxz2Vb2n0s',
    appId: '1:100273539833:android:4e60124767954aeac93028',
    messagingSenderId: '100273539833',
    projectId: 'sikode-app',
    storageBucket: 'sikode-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfICObC-xJy0jWDly1Bd5P4VlRz5ev7yI',
    appId: '1:100273539833:ios:ad03b4b0d50f547ac93028',
    messagingSenderId: '100273539833',
    projectId: 'sikode-app',
    storageBucket: 'sikode-app.appspot.com',
    iosBundleId: 'com.example.sikode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfICObC-xJy0jWDly1Bd5P4VlRz5ev7yI',
    appId: '1:100273539833:ios:ad03b4b0d50f547ac93028',
    messagingSenderId: '100273539833',
    projectId: 'sikode-app',
    storageBucket: 'sikode-app.appspot.com',
    iosBundleId: 'com.example.sikode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnVlIbneXosHAkUYSVFFDuvgadnQeOCm4',
    appId: '1:100273539833:web:4eaf348478b0d3f9c93028',
    messagingSenderId: '100273539833',
    projectId: 'sikode-app',
    authDomain: 'sikode-app.firebaseapp.com',
    storageBucket: 'sikode-app.appspot.com',
  );
}
